name: Create Specification Document

# The workflow is triggered by pull request, push to main, and manual dispatch.
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version, e.g. X.Y.Z:'
        required: true
        type: string
      revision_mark:
          description: 'Set revision mark as Draft, Release or Stable:'
          required: true
          type: string
          default: 'Draft'
      prerelease:
        description: 'Tag as a pre-release?'
        required: false
        type: boolean
        default: true
      draft:
        description: 'Create release as a draft?'
        required: false
        type: boolean
        default: false
  pull_request:
  push:
    branches:
      - main

# Cancel any older workflow runs for PRs that are still in progress, so
# pushing quickly several times does not create too much load.
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.number) || format('run-{0}', github.run_id) }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.2
      with:
        submodules: recursive
    - name: Run build
      run: make docker-pull-latest build
      env:
        VERSION: v${{ github.event.inputs.version }}
        REVMARK: ${{ github.event.inputs.revision_mark }}
    - name: Upload artifacts
      uses: actions/upload-artifact@v4.4.3
      with:
        name: riscv-asm-manual
        path: |
            build/riscv-asm.pdf
            build/riscv-asm.html

  draft-release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4.1.8
        with:
          path: ./
      - name: Get current date
        id: date
        run: echo "RELEASE_DATE=$(date --utc +'%Y%m%d')" >> $GITHUB_OUTPUT
      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v2.1.0
        with:
          draft: true
          name: Draft release ${{ steps.date.outputs.RELEASE_DATE }}
          body: Snapshot (${{ github.sha }})
          files: |
            riscv-asm-manual/riscv-asm.pdf
            riscv-asm-manual/riscv-asm.html
